### ISSUE TITLE
Random test failures

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-endorser-service#25]
When running a full integration test suite some tests periodically fail.

It looks like a timing issue, usually establishing the initial connection between the endorser and author, however occasionally it looks like the transaction trips up.

I already found/fixed a few issues but it looks like there is at least one timing issue still in the integration tests ...

**Comment by Gavinok** [comment]
One issue I've seen related to this is an error from the author wallet service

> UTC [1469] FATAL:  sorry, too many clients already

**Comment by esune** [comment]
Closing since the issue seems mostly resolved, and it is currently not easily reproducible. Will reopen if/when this becomes more frequent.
