### ISSUE TITLE
Granular endorser configuration

### ISSUE THREAD

**Issue by esune** [hyperledger/aries-endorser-service#32]
The endorser service supports auto-endorsing specific types of transaction, however it is not designed to support more fine-grained control mechanisms that would be necessary when running in production.

This issue aims to outline the desired target behaviour, and propose a design that should accommodate most if not all all configuration needs.

## Assumptions
* Endorsers can be configured globally to automatically accept incoming connections and to auto-endorse transactions using settings exposed by ACA-Py (see [here](https://github.com/hyperledger/aries-cloudagent-python/blob/73ba85d07fd1b557d6f6cf4d3701e733bf3d3e3f/Endorser.md))
* Endorser can automatically approve specific types of transactions (see https://github.com/hyperledger/aries-endorser-service/pull/23))
* Endorsers for production networks should follow a "deny by default" policy: new connection requests and transaction endorsement requests will always require approval from an endorser administrator.

## Improvements
* Connections originating from known DIDs or hosts (e.g.: in case of tenants of a known agency) may be automatically accepted following an allow list.
* A permission matrix will be used to define whether the DID can be published to the ledger or not, and how to handle endorsement requests for Schema/CredDef/Revreg/RevRegEntry (`AUTO`, `MANUAL`, `DENY`)
* An allow list will be used to further narrow down which schemas a specific DID is allowed to request endorsement for. Wildcards (`*`) can be used to make the restriction looser.
* An allow list will be used to further narrow down which credential definitions a specific DID is allowed to request endorsement for. Wildcards (`*`) can be used to make the restriction looser.

_Note:_ I can't think of a good reason to prevent an issuer from publishing a credential definition (and related revocation registry and entries), so the assumption is made that revocation-related endorsement requests will follow the rules and permissions enforced by the ledger, without additional filtering/handling. More thinking may be required if there are good reasons to selectively block/allow endorsement requests for these object types.

### Data structures
The following is an initial draft of the data structures required to support the above functionality.

**connection-allow-list**
|Source|
|---|
|https://my-multi-tenant.something.domain |
|XpgeQa93eZvGSZBZef3PHn|

**permission-matrix**
|DID|Public|Schema|CredDef|
|---|---|---|---|
|Ui6HA36FvN83cEtmYYHxrn|True|MANUAL|AUTO
|NCwGwDrzbZEqesYQummzWW|False|MANUAL|MANUAL|

**schema-allow-list**
|DID|Name|Version|
|---|---|---|
|Ui6HA36FvN83cEtmYYHxrn|my-schema|0.1.0|
|Ui6HA36FvN83cEtmYYHxrn|my-schema|0.2.0|
|NCwGwDrzbZEqesYQummzWW|another-schema|*|
|NCwGwDrzbZEqesYQummzWW|my-schema|0.2.0|

**credential-definition-allow-list**
|DID|Schema Issuer DID|Schema Name|Schema Version|Tag|
|---|---|---|---|---|
|Ui6HA36FvN83cEtmYYHxrn|Ui6HA36FvN83cEtmYYHxrn|my-schema|0.2.0|demo|
|NCwGwDrzbZEqesYQummzWW|Ui6HA36FvN83cEtmYYHxrn|my-schema|0.2.0|something-else|

### Updating and managing state
The endorser will expose secured API endpoints to update each one of the data structures. The data will be uploaded to the service as a `.csv` file (with header row) containing the latest snapshot data for the permissions and allow lists. The update process will drop the previous table contents and load the new data. Mechanisms to prevent/limit failure due to partially bad data should be implemented.

This approach has the the following benefits:
* it allows permission data to be managed externally, without the (immediate) requirement for a UI
* it allows bulk data loading and updating via ETL-like processes
* a UI could be easily implemented by extending the endpoints to support basic CRUD operations
* it allows for the source data to be kept private, if necessary, and pushed to the endorser as-needed

*Example:* the `.csv` files are maintained and stored in a GitHub repository. Pull requests are used to update them, allowing an easy review process for changes. GitHub natively displays `.csv` files as tables, allowing searching and filtering. On `merge`, a GHA can be triggered to automatically POST the new files to the target endorser(s).

**Comment by swcurran** [comment]
As discussed with @esune — I disgree with the model of the allow lists being pushed to the Aries Endorser service. I would prefer that they be pulled by the Aries Endorser Service.

In my preferred model, an Aries Endorser Service has a base URL for where it will find the allow list(s), and when needed updates its local copy with the latest allow lists.

Here’s why I think that’s a better approach:

1. The Aries Endorser Service (AES) becomes stateless. On startup or on first (and as needed subsequent) use, it pulls the CSV file(s) needed. On the downside, it does mean it has to “poll” the source, but it can do that both periodically, and when it finds a request not on the allow list — it can get an update from the source just to be sure it wasn’t just added to the list. I do think it would be helpful to have an optional endpoint in the service that is just a “hey, the allow lists have been updated” to trigger the AES to grab an update.

2. The AES is by definition an active component, whereas the source of the Allow Lists may or may not be. For example, the Allow Lists may be managed manually, or may be (for example) generated from GitHub.  The source of the allow lists are produced from a Governance process — a business process, and not necessarily from a service. This eliminates the requirement for any sort of automation on the business process (although automation is, of course, possible).

3. One of the components — the AES, or the source of the CSVs has to be built to “know” about the other. I think it is easier if that it is the AES, and the source of the CSVs just has to be sure to put the files in the right place — anyway it can.

4. The error handling is ugly if the source of the CSVs can’t contact the Aries Endorser Service. Suppose the source is a GHA that is triggered by a merge. If the Aries Mediator Service is down, it is harder to organize an update. Worse is a person is manually uploading the file.  If the CSVs just have to put somewhere known, the Aries Endorser Service can pick them up at its leisure.

5. In our (BC Gov) environment, we’re going to have a bunch of Endorsers. I think it is going to be more of a pain to have to configure separate tasks to update each Endorser vs. just including the location of the Endorser’s files in the AES configuration.

**Comment by swcurran** [comment]
I think it would be helpful if the Aries Endorser Service could have an optional webhook that notified a listener that a transaction was endorsed.

**Comment by swcurran** [comment]
I think it is necessary that there be a control on endorsing or not a specific credential definition (in contrast to the current “Note” in the design). A service should not be able to issue any type of credential. I agree that once an issuer has written a credential definition to the ledger, RevRegDefs and RevRegEntries related to that CredDef must be auto endorsed.

**Comment by WadeBarnes** [comment]
> Note: I can't think of a good reason to prevent an issuer from publishing a credential definition (and related revocation registry and entries), so the assumption is made that revocation-related endorsement requests will follow the rules and permissions enforced by the ledger, without additional filtering/handling. More thinking may be required if there are good reasons to selectively block/allow endorsement requests for these object types.

Endorser permissions should be explicit, not implicit, and include all types of transactions an author can write.  In the case an endorser decides to no longer endorse a particular author's transactions it needs a way the stop all transactions from being endorsed, that includes Revreg and RevRegEntry transactions.  The permission matrix should stand as the most recent record of the permissions and include authors who's permissions have been revoked.

**Comment by WadeBarnes** [comment]
> As discussed with @esune — I disgree with the model of the allow lists being pushed to the Aries Endorser service. I would prefer that they be pulled by the Aries Endorser Service.
> 
> In my preferred model, an Aries Endorser Service has a base URL for where it will find the allow list(s), and when needed updates its local copy with the latest allow lists.
> 
> Here’s why I think that’s a better approach:
> 
> 1. The Aries Endorser Service (AES) becomes stateless. On startup or on first (and as needed subsequent) use, it pulls the CSV file(s) needed. On the downside, it does mean it has to “poll” the source, but it can do that both periodically, and when it finds a request not on the allow list — it can get an update from the source just to be sure it wasn’t just added to the list. I do think it would be helpful to have an optional endpoint in the service that is just a “hey, the allow lists have been updated” to trigger the AES to grab an update.
> 2. The AES is by definition an active component, whereas the source of the Allow Lists may or may not be. For example, the Allow Lists may be managed manually, or may be (for example) generated from GitHub.  The source of the allow lists are produced from a Governance process — a business process, and not necessarily from a service. This eliminates the requirement for any sort of automation on the business process (although automation is, of course, possible).
> 3. One of the components — the AES, or the source of the CSVs has to be built to “know” about the other. I think it is easier if that it is the AES, and the source of the CSVs just has to be sure to put the files in the right place — anyway it can.
> 4. The error handling is ugly if the source of the CSVs can’t contact the Aries Endorser Service. Suppose the source is a GHA that is triggered by a merge. If the Aries Mediator Service is down, it is harder to organize an update. Worse is a person is manually uploading the file.  If the CSVs just have to put somewhere known, the Aries Endorser Service can pick them up at its leisure.
> 5. In our (BC Gov) environment, we’re going to have a bunch of Endorsers. I think it is going to be more of a pain to have to configure separate tasks to update each Endorser vs. just including the location of the Endorser’s files in the AES configuration.

I'm of the opinion the AES needs both push and pull options.

The major downside to having a pull (poll) only option is getting updates in real-time.  Mitigating this issue means having to poll frequently, which requires extra wasteful processing, which we'd like to avoid.  Additionally the service hosting the allow lists could be down for an extended period of time.

The major downside of having a push only option is basically the same, you can miss updates because AES is down or the service pushing the updates is down at the time of the update.  Mitigating the issues in this case is more complicated.

- There should be a centralized process managed in AES for updating the allow list(s).  AES should fetch the changes.
- AES should check for updates on startup.
- AES should poll periodically, at a low frequency (TBD), for configuration updates.
- AES should expose a protected webhook to be used to notify it of allow list updates.  This webhook should allow the caller to specify the URL of the allow list(s) in the case they need to be pulled from a different location than defined by the AES configuration.

This way you get the best of both worlds.  Updates to the allow list(s), automated or manual, can trigger a call to the webhook telling to update it's allow list(s) in real-time.  As a backup AES would poll for updates to ensure the allow list(s) are up to date.  In the case we need to force an update, we can manually call the webhook (or reprocess an automated trigger) rather than restarting AES.

**Comment by WadeBarnes** [comment]
> 1. ... “poll” the source ... when it finds a request not on the allow list ...
I think we should either avoid this or make this behavior optional (my preference is to make it optional).  This likely won't scale well.

**Comment by swcurran** [comment]
> > Emiliano wrote:
> > Note: I can't think of a good reason to prevent an issuer from publishing a credential definition (and related revocation registry and entries), so the assumption is made that revocation-related endorsement requests will follow the rules and permissions enforced by the ledger, without additional filtering/handling. More thinking may be required if there are good reasons to selectively block/allow endorsement requests for these object types.
> 
> > Stephen wrote:
> > I think it is necessary that there be a control on endorsing or not a specific credential definition (in contrast to the current “Note” in the design). A service should not be able to issue any type of credential. I agree that once an issuer has written a credential definition to the ledger, RevRegDefs and RevRegEntries related to that CredDef must be auto endorsed.
> 
> Endorser permissions should be explicit, not implicit, and include all types of transactions an author can write. In the case an endorser decides to no longer endorse a particular author's transactions it needs a way the stop all transactions from being endorsed, that includes Revreg and RevRegEntry transactions. The permission matrix should stand as the most recent record of the permissions and include authors who's permissions have been revoked.

The earlier comments were made prior to the new approach we’ve defined with the fine-grained allow lists. The new approach is on a per object basis — specific DIDs, schemas, and credDefs.  With a CredDef comes permission for the endorsing of the RevReg, but if the CredDef is removed from the allow list, the RevRegs would similarly be removed.

**Comment by WadeBarnes** [comment]
> > > Emiliano wrote:
> > > Note: I can't think of a good reason to prevent an issuer from publishing a credential definition (and related revocation registry and entries), so the assumption is made that revocation-related endorsement requests will follow the rules and permissions enforced by the ledger, without additional filtering/handling. More thinking may be required if there are good reasons to selectively block/allow endorsement requests for these object types.
> > 
> > 
> > > Stephen wrote:
> > > I think it is necessary that there be a control on endorsing or not a specific credential definition (in contrast to the current “Note” in the design). A service should not be able to issue any type of credential. I agree that once an issuer has written a credential definition to the ledger, RevRegDefs and RevRegEntries related to that CredDef must be auto endorsed.
> > 
> > 
> > Endorser permissions should be explicit, not implicit, and include all types of transactions an author can write. In the case an endorser decides to no longer endorse a particular author's transactions it needs a way the stop all transactions from being endorsed, that includes Revreg and RevRegEntry transactions. The permission matrix should stand as the most recent record of the permissions and include authors who's permissions have been revoked.
> 
> The earlier comments were made prior to the new approach we’ve defined with the fine-grained allow lists. The new approach is on a per object basis — specific DIDs, schemas, and credDefs. With a CredDef comes permission for the endorsing of the RevReg, but if the CredDef is removed from the allow list, the RevRegs would similarly be removed.

But that leaves things with the RevRegDefs and RevRegEntries implicit and based on the permissions of the associated CredDef, which imposes artificial restrictions.  What if there were a scenario where an endorser wants to revoke an authors ability to write any new Schemas, CredDefs, and RevRegDefs, but wants to allow them to continue to manage their existing issued credentials by allowing them to continue to write RevRegEntries?  Or even, continue to issue credentials and manage the associated RevRegDefs and RevRegEntries.

**Comment by swcurran** [comment]
Because the authority is based on an explicit CredDefId, not based on their “role”.  No one gets “write schema” permission in this model — they only get permission to “write this particular Schema”.  So as long as they keep permission on the credDefId in question, they can’t rewrite the CredDef (it would be a new one), but they do retain RevReg permissions. Or, we remove the “credDefId” from the allowlist and they can’t even do that.

**Comment by esune** [comment]
Responding in two sections

## Update Strategy/Architecture
I really don't like the pull/polling mechanism, especially combined with a stateless service architecture, for a few reasons:
- if the file hosting platform is down or has an outage during a rule fetch request, there will be no rules to apply. The only way to handle this is rejecting requests, which is not great (the outage is being pushed downstream, by the file hosting service to the Endorser).
- it makes it way more complicated to know when a change in the rules was applied/activated. When troubleshooting issues, it would be extremely difficult to determine what was the ruleset in place at the time of the request. 
- pulling logic is inherently more complicated than exposing an API endpoint that is only utilized when needed, if needed. It also actually adds a dependency, since the system is now not isolated, but requires a specific type of infrastructure setup to run and work (a file hosted with a public URL).
- what if for whatever reason the ruleset cannot be public?). Updates also cannot be triggered on demand, unless further complexity is added at development time, to handle this exception.
- if an automation job pushing to the endpoints fails, there are  multiple easy ways to recover (at least two): kick-off the same automation job again, or manually push the file. Keep in mind most automated jobs already have failure reporting in-place (e.g.: GHA will notify admins if a workflow fails).
- lastly, if polling from a URL became REALLY necessary, once could implement a *separate* microservice responsible for handling that and pushing the file to the Endorser service APIs, leaving the endorser with the on;y responsibility to deal with endorsement requests.

## Permissions
The way I initially thought of this, for simplicity, was to have configuration files be extremely simple: if a rule allowing the operation isn't in the current configuration file, the operation has to be manually approved (or rejected). I realized this is not actually going to always work, as there are scenarios where it will be necessary/desirable to give an author permission to publish whatever they want to a ledger (e.g.: development/test ledgers). This is only achievable with the use of wildcards, that will provide broader matching, but keep the ruleset specific.
This conflicts in particular with this statement:
>  the authority is based on an explicit CredDefId, not based on their “role”. No one gets “write schema” permission in this model — they only get permission to “write this particular Schema”

I think the permission matrix will act as root for all the rules, meaning we should enforce foreign keys in `schema-allow-list` and `credential-definition-allow-list` referencing DIDs in the permission matrix. The matrix could then either have the permissions turned "off" (set to `DENY`) or have the record for a specific DID deleted, and the outcome would be the same: endorsing a request for that DID would not be executed automatically and would require admin input. Each endorser manager could decide what to do (keep a history as @WadeBarnes suggests, or always have the latest state and nothing more).

I am still uncertain about what scenarios could arise where the following situations would be necessary (quoting Wade):
> Revoking endorsement of a RevRegDef stops an author from issuing any more credentials once their current RevRegDefs are full.
Revoking endorsement of a RevRegEntries stops an author from revoking existing credentials.

Adding two more columns in the permission matrix to allow for top-level permissions for a DID would be easy, but would not be applicable on a per-credential definition basis. The permissions would have to be set at the credential definition allow list level and my concern is that it might make things more complicated than they need to be (at least at this time). This item is the one making me scratch my head pretty hard 🤔

**Comment by swcurran** [comment]
While I agree with your pull/polling concerns in a generic use case, here the use case is pretty specific.  Rules will rarely change, and in fact, will be rarely checked.  As such, the ramification of the service not being available and rejecting the event are not really a concern.  Consider:

- A request to write a schema will (usually) happen only after the governance process has been completed. If the issuer sends the request before that, the request will be rejected — and the issuer should handle that. If the file service holding the allow lists happens to be down at the time of the request, it will be rejected, and the issuers handling will also cover that.
- One the request to write the schema is approved and completed — there will never be another request to write the schema, so it really doesn’t matter if the file service is present. And if the request comes again and is accepted — the transaction will not be written since the schema already exists. No harm, no foul.
- Likewise for a credential definition, but with a difference. Once the credential definition is written, it is because it is on the allow list. If the file service is not available in future when requesting approvals for RevReg updates — no problem. The CredDef will already be on the allowlist, so the “polling” will be unnecessary (and won’t happen because it will be found without polling).

Regards revoking endorsment of a RevRegDef or Entries.  I’m suggesting there be no such concept. As long as a “CredDef” is approved for an issuer, they can write RevRegDefs and Entries for that CredDef. If for some reason, the CredDef should be deliberately removed from the AllowList, then the Issuer can no longer write RevRegDefs or Entries. But that is a decision of the Governance/Policy folks to deliberately remove the already written CredDef from the AllowList. And they must have a good reason...

**Comment by WadeBarnes** [comment]
My two cents on the RevRegDef and RevRegEntry discussion ...

If you do not include them explicitly in the allow lists, you will end up hard coding a set of governance rules defining how to handle them in relation to what you do with the associated CredDef.  Those rules will be a single interpretation of how to handle a complex problem, and that's not going to work for every situation.

If you include them explicitly in the allow list you allow, the endorser configure the rules to conform to the governance rules they are following.

**Comment by WadeBarnes** [comment]
From listening to some of the discussion on the AWG I think it would be easy to extend the wildcards to the DIDs, at all allow levels; allow all connections, allow a DID to request endorsement on all objects types.

**Comment by swcurran** [comment]
Good discussion on the Aries Working Group call today.  I now understand the manual mode — a webhook, and holding on to the request until there is a response. No UI — that would be a YAApp (Yet Another App). Easy enough.

I still don’t like the overhead of allow lists for RevRegs as in the vast majority of cases, if you are an issuer (e.g., can create a CredDef), you must be able to create RevReg* objects. It will be extremely weird that such a feature would be turned off, and I think turning it off can be done in other ways.  But whatever… :-).  Definitely not a hill worth dying on.

Same with the poll/pull.  Over to the implementer :-).

**Comment by WadeBarnes** [comment]
Perhaps there is a compromise.  What if we supported the explicit allow list definition for RevRegDefs and RevRegEntries, but also had a sensible default behavior?  It may be that 90% of the time people opt for the defaults, but the options are there for those that require the extra control.

**Comment by ianco** [comment]
I think there are 2 topics for discussion, and maybe they can be separated and we can have 2 separate tickets/development efforts.

1.  What are the permissions that the Endorser is to implement?  (allow or deny?  in general or by specific connection and transaction type?  etc ...)  I suggest to add these within the existing Endorser (stored in a database table from my recollection) and implement the actual controls in the Endorser (i.e. what the Endorser does when it receives a request).  There is an existing web service (from my recollection) to update these permissions, so for this stage just make sure the web service 

2.  How are the updates managed?  This is the push vs pull discussion, and what is the file format etc.

3.  Webhooks - I suggest dealing with this as a separate work effort, we implemented it for OrgBook and it's more complicated than you think ...
4.

**Comment by esune** [comment]
> I think there are 2 topics for discussion, and maybe they can be separated and we can have 2 separate tickets/development efforts.
> 
>     1. What are the permissions that the Endorser is to implement?  (allow or deny?  in general or by specific connection and transaction type?  etc ...)  I suggest to add these within the existing Endorser (stored in a database table from my recollection) and implement the actual controls in the Endorser (i.e. what the Endorser does when it receives a request).  There is an existing web service (from my recollection) to update these permissions, so for this stage just make sure the web service
> 
>     2. How are the updates managed?  This is the push vs pull discussion, and what is the file format etc.
> 
>     3. Webhooks - I suggest dealing with this as a separate work effort, we implemented it for OrgBook and it's more complicated than you think ...

100% agree about webhooks being generally more complicated than expected, and leaving them for a later discussion/issue.

Updates and business logic are relatively tightly coupled in my opinion, since it will be necessary to update the configurations in order for the endorser to be able to make decisions.

**Comment by esune** [comment]
After further discussion with @swcurran @WadeBarnes and @Gavinok, and following @ianco's recommendations, we landed on the following:

- There will be an allow list for publishing DIDs
- There will be an allow list for publishing schema definitions
- There will be an allow list for publishing credential definitions
- Basic CRUD will be implemented for the above lists
- A global flag `REJECT_BY_DEFAULT` will control whether transactions that do not match allow list permissions will be rejected by default, or left pending
- Updating an allow list should trigger re-processing of all currently pending transactions

Possible models supporting the above:

**public-did-allow-list**
|DID|
|---|
|Ui6HA36FvN83cEtmYYHxrn|
|NCwGwDrzbZEqesYQummzWW|

**schema-allow-list**
|DID|Name|Version|
|---|---|---|
|Ui6HA36FvN83cEtmYYHxrn|my-schema|0.1.0|
|Ui6HA36FvN83cEtmYYHxrn|my-schema|0.2.0|
|NCwGwDrzbZEqesYQummzWW|another-schema|*|
|NCwGwDrzbZEqesYQummzWW|my-schema|0.2.0|

**credential-definition-allow-list**
|DID|Schema Issuer DID|Schema Name|Schema Version|Tag|RevRegDef|RevRegEntry
|---|---|---|---|---|---|---|
|Ui6HA36FvN83cEtmYYHxrn|Ui6HA36FvN83cEtmYYHxrn|my-schema|0.2.0|demo|true|true
|NCwGwDrzbZEqesYQummzWW|Ui6HA36FvN83cEtmYYHxrn|my-schema|0.2.0|something-else|false|false

Note.: the last two columns on the `credential-definition-allow-list` should default to true and could be switched to false to control whether new revocation registries can be created/published and/or revocation entries can be published.

**Comment by swcurran** [comment]
@esune — how about a push/pull compromise like this.  There would be configurations that would indicate the location of the allow lists — a base URL, with a fixed set of file names for the DID, Schema and CredDef allow lists.  On startup read the files, and on a request for endorsement that fails, read from the files and retry. Plus we have an endpoint that is a simple “load”, that retrieves the current lists when triggered.  I think if we did that we’d have all we need and we might not need the persistence.
