### ISSUE TITLE
Update author agent to support new acapy version

### ISSUE THREAD

**Issue by Gavinok** [hyperledger/aries-endorser-service#39]
https://github.com/hyperledger/aries-endorser-service/pull/35 updated the aca-py version and there seems to be issues with the author agent failing the bdd tests.

The first exception originating from
```
ModuleNotFoundError: No module named 'indy'
```

**Comment by WadeBarnes** [comment]
That update switched to an askar only image, from an image that contained the indy-sdk.  Do the tests need to be updated to account for this change?  We're migrating everything away from containing the indy-sdk.

**Comment by Gavinok** [comment]
I think so, I haven't had the time to dig deeper into this yet.

**Comment by Gavinok** [comment]
Closed with #49
